# Generated by Django 6.0.6 on 2026-06-23 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Key Activities',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyResultArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Key Result Area',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=500)),
                ('logo', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Delayed', 'Delayed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpectedOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expected_outputs', to='projects.keyactivity')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutputIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expected_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_indicators', to='projects.expectedoutput')),
                ('key_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_indicators', to='projects.keyactivity')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_1', models.FloatField(blank=True, null=True)),
                ('year_2', models.FloatField(blank=True, null=True)),
                ('year_3', models.FloatField(blank=True, null=True)),
                ('year_4', models.FloatField(blank=True, null=True)),
                ('year_5', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('output_indicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='projects.outputindicator')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='project_documents/')),
                ('size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kra_ids', models.JSONField(blank=True, default=list)),
                ('objective_ids', models.JSONField(blank=True, default=list)),
                ('strategy_ids', models.JSONField(blank=True, default=list)),
                ('key_activity_ids', models.JSONField(blank=True, default=list)),
                ('expected_output_ids', models.JSONField(blank=True, default=list)),
                ('output_indicator_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key_result_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='projects.keyresultarea')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategic_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='projects.strategicobjective')),
            ],
            options={
                'verbose_name_plural': 'Strategies',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='outputindicator',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_indicators', to='projects.strategy'),
        ),
        migrations.AddField(
            model_name='keyactivity',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_activities', to='projects.strategy'),
        ),
        migrations.AddField(
            model_name='expectedoutput',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_outputs', to='projects.strategy'),
        ),
        migrations.CreateModel(
            name='IndicatorTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('baseline_reference', models.FloatField(blank=True, null=True)),
                ('target', models.FloatField(blank=True, null=True)),
                ('achievement', models.TextField(blank=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('evidence_name', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='projects.outputindicator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='projects.project')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('project', 'output_indicator', 'year')},
            },
        ),
    ]
