# Generated by Django 5.2.4 on 2026-07-09 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_technicalreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completion_rate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='disbursed_amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sustainability',
        ),
        migrations.RemoveField(
            model_name='project',
            name='utilized_amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vmgs',
        ),
        migrations.RemoveField(
            model_name='projectdocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='projectdocument',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='projectdocument',
            name='size',
        ),
        migrations.AddField(
            model_name='project',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='men',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalreport',
            name='financial_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='technicalreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_reports', to='projects.project'),
        ),
        migrations.AddField(
            model_name='technicalreport',
            name='quarter',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_documents/')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.projectdocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
