# Generated by Django 5.2.4 on 2026-09-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_activityindicator_main_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Suspended', 'Suspended'), ('Delayed', 'Delayed'), ('Pending', 'Pending'), ('Terminated', 'Terminated')], default='Not Started', max_length=20),
        ),
    ]
