# Generated by Django 5.2.4 on 2026-09-16 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_technicalreport_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatortracking',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='IndicatorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_id', models.CharField(max_length=64)),
                ('indicator_name', models.CharField(max_length=500)),
                ('target', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reported_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('achievement', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('reason_for_zero', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technical_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_reports', to='projects.technicalreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorReportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='technical_report_evidence/')),
                ('name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='projects.indicatorreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='indicatorreport',
            constraint=models.UniqueConstraint(fields=('technical_report', 'indicator_id'), name='unique_indicator_report_per_technical_report'),
        ),
    ]
