# Generated by Django 5.2.4 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_indicatortracking_remarks_indicatorreport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalreport",
            name="report_group_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalreport",
            name="selected_locations",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
