# Generated by Django 5.2.4 on 2026-09-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_technicalreport_group_and_selected_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalreport',
            name='status',
        ),
    ]
