# Generated by Django 5.2.4 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_remove_technicalreport_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Submitted", "Submitted"),
                    ("Under Review", "Under Review"),
                    ("Approved", "Approved"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
