# Generated by Django 5.2.4 on 2026-09-17 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_technicalreport_context_key'),
        ('user_management', '0007_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='co_principal_investigators',
            field=models.ManyToManyField(blank=True, related_name='co_principal_investigator_projects', to='user_management.useraccount'),
        ),
        migrations.AddField(
            model_name='project',
            name='coordinator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_projects', to='user_management.useraccount'),
        ),
        migrations.AddField(
            model_name='project',
            name='investigator_institutes',
            field=models.ManyToManyField(blank=True, related_name='investigator_projects', to='user_management.institute'),
        ),
        migrations.AddField(
            model_name='project',
            name='main_project',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='principal_investigators',
            field=models.ManyToManyField(blank=True, related_name='principal_investigator_projects', to='user_management.useraccount'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to='user_management.useraccount'),
        ),
        migrations.AddField(
            model_name='technicalreport',
            name='original_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value_chain_lead_copy', to='projects.technicalreport'),
        ),
        migrations.AlterField(
            model_name='technicalreport',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted to Accountant', 'Submitted to Accountant'), ('Rejected by Accountant', 'Rejected by Accountant'), ('Approved by Accountant', 'Approved by Accountant'), ('Submitted to Project Coordinator', 'Submitted to Project Coordinator'), ('Rejected by Project Coordinator', 'Rejected by Project Coordinator'), ('Approved by Project Coordinator', 'Approved by Project Coordinator'), ('Submitted to M&E', 'Submitted to M&E'), ('Rejected by M&E', 'Rejected by M&E'), ('Approved/Finalized', 'Approved/Finalized')], default='Draft', max_length=60),
        ),
        migrations.CreateModel(
            name='ReportWorkflowAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('user_role', models.CharField(max_length=80)),
                ('previous_status', models.CharField(max_length=80)),
                ('new_status', models.CharField(max_length=80)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_audit', to='projects.technicalreport')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.useraccount')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to='user_management.useraccount')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.technicalreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
