# Generated by Django 5.2.4 on 2026-09-18 06:55

import django.db.models.deletion
from django.db import migrations, models


def backfill_main_projects(apps, schema_editor):
    MainProject = apps.get_model("projects", "MainProject")
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all().iterator():
        name = project.main_project or project.project_name
        parent, _ = MainProject.objects.get_or_create(
            name=name,
            defaults={
                "logo": project.logo,
                "description": project.description,
                "start_date": project.start_date,
                "end_date": project.end_date,
                "status": project.status,
            },
        )
        project.main_project_record_id = parent.id
        project.save(update_fields=["main_project_record"])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_project_co_principal_investigators_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('logo', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Suspended', 'Suspended'), ('Delayed', 'Delayed'), ('Pending', 'Pending'), ('Terminated', 'Terminated')], default='Not Started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='main_project_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_titles', to='projects.mainproject'),
        ),
        migrations.RunPython(backfill_main_projects, migrations.RunPython.noop),
    ]
