# Generated by Django 5.2.4 on 2026-09-15 09:16

from django.db import migrations, models


ROLE_DATA = [
    ("system_admin", "System Admin"),
    ("national_me", "National M&E"),
    ("high_level", "High Level"),
    ("business_logic", "Business Logic"),
    ("project_manager", "Project Manager"),
    ("department_head", "Department Head"),
    ("staff_user", "Staff User"),
    ("value_chain_leads", "Value Chain Leads"),
]


def migrate_legacy_roles(apps, schema_editor):
    Role = apps.get_model("user_management", "Role")
    UserAccount = apps.get_model("user_management", "UserAccount")
    roles = {key: Role.objects.create(key=key, name=name) for key, name in ROLE_DATA}
    for user in UserAccount.objects.all():
        role = roles.get(user.role)
        if role:
            user.roles.add(role)


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_useraccount_value_chains_and_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='useraccount',
            name='personal_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='user_management.role'),
        ),
        migrations.RunPython(migrate_legacy_roles, migrations.RunPython.noop),
    ]
