# Generated by Django 5.2.4 on 2026-09-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('value_chain_lead', 'Value Chain Lead'), ('accountant', 'Accountant'), ('project_coordinator', 'Project-Coordinator'), ('me', 'M&E'), ('principal_investigator', 'Principal Investigator'), ('co_principal_investigator', 'Co-principal investigator'), ('staff_user', 'Staff User')], max_length=50),
        ),
    ]
